version: 1.0.{build}

image: macos-sonoma

build_script:

- cmd: echo "AppVeyor"

test: off

#---------------------------------#

#  Skip builds for doc changes    #

#---------------------------------#

skip_commits:

  # Regex for matching commit message

  message: /\(doc\).*/

environment:
  APPVEYOR_VNC_PASSWORD: e-gEC?Cp6WqVeeRL3Dkn

on_finish:
  - sh: export APPVEYOR_VNC_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-vnc.sh' | bash -e -
